<script>
  import PageTitle from "$lib/components/PageTitle.svelte";
  import AiIndicator from "$lib/components/AiIndicator.svelte";
  import Divider from "$lib/components/Divider.svelte";
</script>

<PageTitle
  title="How I use LLMs to write"
  subtitle="Transaprency if for me very important. Let's talk about LLMs and how I use them."
/>

<Divider />

<h2>What does this mean?</h2>

<AiIndicator humanLevel={100} />
<p>
  This means that the content is 100% human written. With all the possible
  imperfections like grammatical errors and typos.
</p>

<AiIndicator humanLevel={90} />
<p>
  The content is 100% written by me, but a LLM made the proof reading, removing
  typos and grammatical errors. But the form is not modified from AI.
</p>

<AiIndicator humanLevel={50} />
<p>
  The content is a mix of sentences written by me and written by AI. During the
  proof reading, the AI likely changed the form of some sentences or made entire
  paragraphs.
</p>

<AiIndicator humanLevel={10} />
<p>
  The content is completely generated by AI. I made only proof reading and
  prompt the topic.
</p>

<Divider />

<h2>Introduction</h2>

<p>Transparency is really important for me.</p>

<p>
  I think that the large use of LLMs (or AI if you prefer) to generate content
  created a sort of sadness among the written content online. Or at least this
  is what I feel.
</p>

<p>
  I was very very Hyped at the beginning, when OpenAI released the version 3 of
  ChatGPT. And I used it also to generate completely the content of my blog.
</p>

<p>
  I started immediately to have a bad feeling. Yes, I was asking for specific
  topics and I was reviewing the text, but... it sounds fake.
</p>

<p>
  I don't know about you, but after some time playing with LLMs and reading a
  lot of AI generated stuff online, I can quite easily spot when a text is
  generated or not.
</p>

<p>
  Then I thought, that like every new stuff that seems disruptive, it brings
  also some good things. It is easy to think that human written content will
  desappear, due to ChatGPT and other LLMs, but what is true is the opposite.
</p>

<p>
  Now, more than ever, human written content is <strong>special</strong> I got a
  really nice feeling now reading a human content instead of a generated one, and
  I give a lot more value to something that comes from a real brain.
</p>

<h2>The Idea</h2>

<p>
  So I stopped using LLMs to generate content, but I started to use it only for
  proof reading and grammatical corrections (I am not english mothertongue). And
  I thought that I would like to know, if I am reading some human content or AI
  generated one.
</p>

<p>
  So the idea: why don't I say it to the reader? Also if there are some AI
  generated parts, it would be much better at least to know it.
</p>

<p>
  You know how much AI touched the content you are reading and how. So you can
  better value what you are reading. And maybe, knowing that a little or no AI
  is involved, you can value more some content, that before could sound not so
  interesting.
</p>

<h2>Take the good part of innovation!</h2>

<p>
  A lot of time, when something disruptive like LLMs comes around, the panic to
  loose what we have kicks in. But in fact, there is always something that we
  can use as advantage. Look for example the possibility for the people to buy
  high end cameras. Everybody is now a photographer, and everybody panic that
  photography was over. The opposite! In the sea of images, know only the real
  good ones comes up, this means that this new thing brought a boost of the
  quality of the best pictures.
</p>

<p>
  For LLMS is the same. Human content is more valuable now, and that's the
  reason of this little information on my blog posts.
</p>
